service: local-aws-testing

provider:
  name: aws
  runtime: nodejs12.x


functions:
  hello:
    handler: src/handler.handler
    events:
      - http:
          path: /{path+}
          method: ANY

plugins:
  - serverless-plugin-typescript
  - serverless-offline