version: "3.1"

services:
  postgres:
    build:
      context: .
      dockerfile: pg.Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
