version: "3.1"

services:
  postgres:
    build:
      context: ./docker
      dockerfile: pg.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_USER: $PGUSER
      POSTGRES_HOST: $PGHOST
      POSTGRES_DB: $PGDATABASE
      POSTGRES_PASSWORD_REP: $PGPASSWORDREP
      POSTGRES_USER_REP: $PGUSEREP
    ports:
      - 5432:5432

  stream_wal2json:
    build:
      context: stream
    depends_on:
      - postgres
      - localstack
    volumes:
      - .:/app:cached
    restart: always
    environment:
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_USER: $PGUSER
      POSTGRES_HOST: $PGHOST
      POSTGRES_DB: $PGDATABASE
      POSTGRES_PASSWORD_REP: $PGPASSWORDREP
      POSTGRES_USER_REP: $PGUSEREP
      PGSSLMODE: disable
      CURRENT_ENV: $CURRENT_ENV
      LOCALSTACK_URL: $LOCALSTACK_URL
      AWS_ACCESS_KEY_ID: $FAKE_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $FAKE_AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      REPLICATION_KINESIS_STREAM_NAME: $REPLICATION_KINESIS_STREAM_NAME_WAL2JSON
      REPLICATION_FIREHOSE_NAME: $REPLICATION_FIREHOSE_NAME_WAL2JSON
      REPLICATION_S3_BUCKET: $REPLICATION_S3_BUCKET_WAL2JSON
      REPLICATION_SLOT_NAME: $REPLICATION_SLOT_NAME_WAL2JSON
      REPLICATION_SLOT_TYPE: $REPLICATION_SLOT_TYPE_WAL2JSON
  transform:
    build:
      context: transform
    depends_on:
      # - postgres
      - localstack
      # - stream_wal2json
    restart: always
    # volumes:
    #   - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_USER: $PGUSER
      POSTGRES_HOST: $PGHOST
      POSTGRES_DB: $PGDATABASE
      POSTGRES_PASSWORD_REP: $PGPASSWORDREP
      POSTGRES_USER_REP: $PGUSEREP
      PGSSLMODE: disable
      CURRENT_ENV: $CURRENT_ENV
      LOCALSTACK_URL: $LOCALSTACK_URL
      AWS_ACCESS_KEY_ID: $FAKE_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $FAKE_AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      REPLICATION_KINESIS_STREAM_NAME: $REPLICATION_KINESIS_STREAM_NAME_WAL2JSON
      REPLICATION_FIREHOSE_NAME: $REPLICATION_FIREHOSE_NAME_WAL2JSON
      REPLICATION_S3_BUCKET: $REPLICATION_S3_BUCKET_WAL2JSON
      REPLICATION_SLOT_NAME: $REPLICATION_SLOT_NAME_WAL2JSON
      REPLICATION_SLOT_TYPE: $REPLICATION_SLOT_TYPE_WAL2JSON
      
  # stream_testdecoding:
  #   build:
  #     context: stream
  #   depends_on:
  #     - postgres
  #     - localstack
  #   volumes:
  #     - .:/app:cached
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: $PGPASSWORD
  #     POSTGRES_USER: $PGUSER
  #     POSTGRES_HOST: $PGHOST
  #     POSTGRES_DB: $PGDATABASE
  #     POSTGRES_PASSWORD_REP: $PGPASSWORDREP
  #     POSTGRES_USER_REP: $PGUSEREP
  #     PGSSLMODE: disable
  #     CURRENT_ENV: $CURRENT_ENV
  #     LOCALSTACK_URL: $LOCALSTACK_URL
  #     AWS_ACCESS_KEY_ID: $FAKE_AWS_ACCESS_KEY_ID
  #     AWS_SECRET_ACCESS_KEY: $FAKE_AWS_SECRET_ACCESS_KEY
  #     AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  #     REPLICATION_KINESIS_STREAM_NAME: $REPLICATION_KINESIS_STREAM_NAME_TESTDECODING
  #     REPLICATION_FIREHOSE_NAME: $REPLICATION_FIREHOSE_NAME_TESTDECODING
  #     REPLICATION_S3_BUCKET: $REPLICATION_S3_BUCKET_TESTDECODING
  #     REPLICATION_SLOT_NAME: $REPLICATION_SLOT_NAME_TESTDECODING
  #     REPLICATION_SLOT_TYPE: $REPLICATION_SLOT_TYPE_TESTDECODING

  localstack:
    image: localstack/localstack:1.0.0
    ports:
      - 4566:4566
    environment:
      DEBUG: ${DEBUG-}
      PERSISTENCE: ${PERSISTENCE-}
      LAMBDA_EXECUTOR: ${LAMBDA_EXECUTOR-}
      # LAMBDA_EXECUTOR: docker localstack start
      # LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY-}  # only required for Pro
      DOCKER_HOST: unix:///var/run/docker.sock
      LOCALSTACK_SERVICES: kinesis,firehose,s3,dynamodb,lambda
      # EAGER_SERVICE_LOADING: 1
      AWS_ACCESS_KEY_ID: $FAKE_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $FAKE_AWS_SECRET_ACCESS_KEY
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_USER: $PGUSER
      POSTGRES_HOST: $PGHOST
      POSTGRES_DB: $PGDATABASE
      POSTGRES_PASSWORD_REP: $PGPASSWORDREP
      POSTGRES_USER_REP: $PGUSEREP
      CURRENT_ENV: $CURRENT_ENV
      REPLICATION_KINESIS_STREAM_NAME_WAL2JSON: $REPLICATION_KINESIS_STREAM_NAME_WAL2JSON
      REPLICATION_FIREHOSE_NAME_WAL2JSON: $REPLICATION_FIREHOSE_NAME_WAL2JSON
      REPLICATION_S3_BUCKET_WAL2JSON: $REPLICATION_S3_BUCKET_WAL2JSON
      REPLICATION_KINESIS_STREAM_NAME_TESTDECODING: $REPLICATION_KINESIS_STREAM_NAME_TESTDECODING
      REPLICATION_FIREHOSE_NAME_TESTDECODING: $REPLICATION_FIREHOSE_NAME_TESTDECODING
      REPLICATION_S3_BUCKET_TESTDECODING: $REPLICATION_S3_BUCKET_TESTDECODING
    volumes:
      - "./docker/init/localstack:/docker-entrypoint-initaws.d"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"