name: msys2

on:
  push:
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: CLANGARM64
    - shell: msys2 {0}
      run: |   
        echo yes | pacman -S mingw-w64-clang-x86_64-ruby
        /clang64/bin/ruby --version
        ls /clangarm64
